---
- name: Create a database
  hosts: node2.lab.example.com

  tasks:
    - name: Cria banco de dados 'araujo'
      mysql_db:
        name: araujo
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
