---
- name: Install mysql server
  hosts: node2.lab.example.com
  become: true

  tasks:
    - name: Install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start mysql-server service
      ansible.builtin.service:
        name: mysql-server
        state: started
        enabled: true
