---
- name: Install mysql server
  hosts: node2.lab.example.com
  become: true
  vars:
    database: mysql
    mysql_pkg: mysql-server
    mysql_svc: mysqld

  tasks:
    - name: Install {{ database }}-server
      ansible.builtin.dnf:
        name: "{{ mysql_pkg }}"
        state: latest

    - name: Start {{ database }} service
      ansible.builtin.service:
        name: "{{ mysql_svc }}"
        state: started
        enabled: true
